version: "3.5"

services: 
  postgres:
      image: postgres:latest
      hostname: db
      environment:
        - POSTGRES_PASSWORD=1234
        - POSTGRES_USER=rzanc
        - POSTGRES_DB=rzanc
      ports:
        - "5432:5432"
      volumes:
        - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      command: 'postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c max_connections=1024 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off' 
      deploy:
        resources:
          limits:
            cpus: "0.45"
            memory: "270MB"    

  netcore01: &api
    image: api:latest
    hostname: netcore01
    environment:
      - PORT=8080
    ports:
      - "8081:8080"
    depends_on:
      - postgres

networks:
  default:
    driver: bridge
    name: garnize
