CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE UNLOGGED TABLE "Clients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Limite" integer NOT NULL,
    "Saldo" integer NOT NULL,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("Id")
);

CREATE UNLOGGED TABLE "Transactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Valor" integer NOT NULL,
    "Tipo" character(1) NOT NULL,
    "Descricao" character varying(10) NOT NULL,
    "IdCliente" integer,
    "Realizada_em" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transactions_Clients_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES "Clients" ("Id")
);

CREATE INDEX "IX_Transactions_IdCliente" ON "Transactions" ("IdCliente");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240217181833_Initial', '8.0.2');

INSERT INTO "Clients" ("Id","Limite","Saldo") VALUES
	 (1,-100000,0),
	 (2,-80000,0),
	 (3,-1000000,0),
	 (4,-10000000,0),
	 (5,-500000,0);

COMMIT;

UPDATE "Clients" SET "Saldo"=0;
DELETE from "Transactions";

